# Custom Language File for Launcher Customizer

[ejs.app]
title = "AlvalitZ RP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Haltarsan/AlvalitZRPLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ykNZgvZ2"

[ejs.settings]
sourceGithubLink = "https://github.com/Haltarsan/AlvalitZRPLauncher"
supportLink = "https://github.com/Haltarsan/AlvalitZRPLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO ALVALITZ RP"
welcomeDescription = "Apocalyptic RP"
welcomeDescCTA = "Enjoy !#"
